<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Course;
use App\Models\Transaction;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class MemberSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Tentukan ID Course tujuan secara spesifik (ID 1 = Bimbingan Manasik Haji Intensif)
        $targetCourseId = 1; 

        $course = Course::find($targetCourseId); 

        if (!$course) {
            $this->command->error("Gagal menjalankan seeder: Kelas dengan ID {$targetCourseId} tidak ditemukan di database!");
            return;
        }

        // =========================================================================
        // PROSES REFRESH KHUSUS MEMBER (Hapus data transaksi & user ber-role member)
        // =========================================================================
        $this->command->info('Memulai proses refresh khusus data member...');

        DB::transaction(function () use ($targetCourseId) {
            // Ambil semua ID user yang memiliki role 'member'
            $memberIds = User::where('role', 'member')->pluck('id')->toArray();

            if (!empty($memberIds)) {
                // A. Ambil semua ID transaksi milik member-member tersebut
                $transactionIds = Transaction::whereIn('user_id', $memberIds)->pluck('id')->toArray();

                if (!empty($transactionIds)) {
                    // B. Hapus relasi di tabel pivot (course_transaction) terlebih dahulu
                    DB::table('course_transaction')->whereIn('transaction_id', $transactionIds)->delete();
                    
                    // C. Hapus data di tabel transactions milik member
                    Transaction::whereIn('id', $transactionIds)->delete();
                }

                // D. Hapus data user yang ber-role member
                User::whereIn('id', $memberIds)->delete();
                
                $this->command->info('Data member lama dan riwayat transaksinya berhasil dibersihkan.');
            }
        });
        // =========================================================================

        $members = [
            ['name' => 'Bibit', 'email' => 'bibittztabiru@gmail.com'],
            ['name' => 'Owi', 'email' => 'nurhasan@iai-tabah.ac.id'],
            ['name' => 'Mira Hikmalasari', 'email' => 'mhikmalasari@gmail.com'],
            ['name' => 'Khoirunnisa', 'email' => 'nisajkt19@gmail.com'],
            ['name' => 'Nur Anita', 'email' => 'nuranita1012@gmail.com'],
            ['name' => 'Nana Rostiana', 'email' => 'rose.tian88@gmail.com'],
            ['name' => 'Lia Rahmawati', 'email' => 'liaagung04@gmail.com'],
            ['name' => 'Maqfirah', 'email' => 'mqhfira@gmail.com'],
            ['name' => 'Delis Sri Maryati', 'email' => 'delis.sri.maryati@gmail.com'],
            ['name' => 'Izzatul Millah AM', 'email' => 'millaamilloo@gmail.com'],
            ['name' => 'Nurjamila Mansyur', 'email' => 'nuruljamila235@gmail.com'],
            ['name' => 'Hayatun Nufus', 'email' => 'nufusjaelani96@gmail.com'],
            ['name' => 'Lisa aspiani tuasikal', 'email' => 'lisaaspianituasikal@gmail.com'],
            ['name' => 'Efrilyana', 'email' => 'maniezz.efril@gmail.com'],
            ['name' => 'Maria Fatmawati', 'email' => 'fatmawatimaria2024@gmail.com'],
            ['name' => 'Arma novika bactiar', 'email' => 'armanovika03@gmail.com'],
            ['name' => 'Muhammad Akhi Falakhi', 'email' => 'akhi.falakhi@gmail.com'],
            ['name' => 'Fisca Ambarwati', 'email' => 'fisca.ambarwati@gmail.com'],
            ['name' => 'Siti rodia julianti', 'email' => 'sitirodiajulianti@gmail.com'],
            ['name' => 'Muhammad Kholid', 'email' => 'muhammadkholid489@gmail.com'],
            ['name' => 'Mildawati', 'email' => 'mildawati@yahoo.com'],
            ['name' => 'Noor Sri Wijayanti', 'email' => 'noor.sriwijayanti@yahoo.com'],
            ['name' => 'Shanti Dwigunawati Indah', 'email' => 'shantindah82@gmail.com'],
            ['name' => 'Khoerunnisa', 'email' => 'ikhoerunnisa61@gmail.com'],
            ['name' => 'Dewi yuliawati', 'email' => 'Dewi_yuliawati20@yahoo.co.id'],
            ['name' => 'Sudarmi', 'email' => 'ahyantita@gmail.com'],
            ['name' => 'Mudrika', 'email' => 'mudrikahnajlaa@gmail.com'],
            ['name' => 'khadiatus solihah', 'email' => 'khadiatus15@gmail.com'],
            ['name' => 'Selvi Astuti', 'email' => 'Selviastutiassa@gmail.com'],
            ['name' => 'Yanti novianti', 'email' => 'yanti2023novianti@gmail.com'],
            ['name' => 'Rani Aprina', 'email' => 'aprinarani@gmail.com'],
            ['name' => 'Zuhur Diana', 'email' => 'zuhurdiana1011@gmail.com'],
            ['name' => 'Ana Safitri', 'email' => 'anasafiitrii@gmail.com'],
            ['name' => 'Daniati Puspita Dewi', 'email' => 'daniatipuspita@gmail.com'],
            ['name' => 'Zakiah', 'email' => 'zakiah.zk47@gmail.com'],
            ['name' => 'APRILIA SUSANTI', 'email' => 'ayahluve80@gmail.com'],
            ['name' => 'Ida Watna', 'email' => 'danandeso79@gmail.com'],
            ['name' => 'Fitriana Ardy', 'email' => 'fitrianaa.ardy@gmail.com'],
            ['name' => 'Hanim Mas\'adah', 'email' => 'hanimmasadah9@gmail.com'],
            ['name' => 'RIRIN FEBRIANI', 'email' => 'ririnfebriani.fcallysta@gmail.com'],
            ['name' => 'IIN NURAINI', 'email' => 'iinnuraini317@gmail.com'],
            ['name' => 'Fita Herawati', 'email' => 'fitaherawati85@gmail.com'],
            ['name' => 'SUCIYANI', 'email' => 'suciyanidarwis22@gmail.com'],
            ['name' => 'Ahmad Sholeh', 'email' => 'ahmads6493.as@gmail.com'],
            ['name' => 'Silvia', 'email' => 'qivaniezz@gmail.com'],
            ['name' => 'Heni Marlina', 'email' => 'fahreza25042013@gmail.com'],
            ['name' => 'Andini Annas Parahita Supriyadi', 'email' => 'andin.parahita@gmail.com'],
            ['name' => 'Umi zulaichah', 'email' => 'Umee.zulaichah@gmail.com'],
            ['name' => 'hj selvi oktaviani', 'email' => 'hjselvioktavianinurularifin@gmail.com'],
            ['name' => 'Alfath Yosiana Putri', 'email' => 'alfath.yputri@gmail.com'],
            ['name' => 'Husnaini', 'email' => 'husnahusnaini19@gmail.com'],
            ['name' => 'Agung Yosi Ardi Evana', 'email' => 'agungyosiardievana@gmail.com'],
            ['name' => 'Fitri Utami Putri', 'email' => 'Putri.utie1989@gmail.com'],
            ['name' => 'MUSTIKA MARNAH', 'email' => 'mustikamarnah@gmail.com'],
            ['name' => 'Mohamad Archyd Ekaputra', 'email' => 'archydekaputra@gmail.com'],
            ['name' => 'Anggi angraini zainul', 'email' => 'anggizainul54@gmail.com'],
            ['name' => 'Tutik Pauziah', 'email' => 'pauziahtutik@gmail.com'],
            ['name' => 'Wahyu Adi Syahputra', 'email' => 'wahyuadi.sy@gmail.com'],
            ['name' => 'Rahmani Arisadita', 'email' => 'rahmani.arisadita@gmail.com'],
            ['name' => 'Fadhilatur Rohmah', 'email' => 'fadhila.rohmah07@gmail.com'],
            ['name' => 'Hanifiya', 'email' => 'hanifiya34@guru.sd.belajar.id'],
            ['name' => 'Panji insani syafaat', 'email' => 'panjisandi30@gmail.com'],
            ['name' => 'Betty Isharyanti', 'email' => 'isharyantibetty23@gmail.com'],
            ['name' => 'Cahya Suharyani', 'email' => 'suharyanicahya@gmail.com'],
            ['name' => 'Rahmawati', 'email' => 'raahmhawati@gmail.com'],
            ['name' => 'Ismi Barokah', 'email' => 'ismibarokah345@gmail.com'],
            ['name' => 'Nurul Chotimah', 'email' => 'nurulchotimah42@gmail.com'],
            ['name' => 'Ida Arafah', 'email' => 'Idaarafah950@gmail.com'],
            ['name' => 'Rosi Pratiwi', 'email' => 'Syalalakitty3@gmail.com'],
            ['name' => 'Abdul Muhsin', 'email' => 'abdul.muhsin029@gmail.com'],
            ['name' => 'Beta permata cahyaningtyas', 'email' => 'betapermata6@gmail.com'],
            ['name' => 'DESY TRI ASTUTY', 'email' => 'Desy201290@gmail.com'],
            ['name' => 'Kamila', 'email' => 'kamila012917m@gmail.com'],
            ['name' => 'Ani Murtini', 'email' => 'anizwan571@gmail.com'],
            ['name' => 'Lina Kusumadita', 'email' => 'linakusumadita@gmail.com'],
            ['name' => 'Titis Kusmawati', 'email' => 'titis.kusmawati@gmail.com'],
            ['name' => 'Nur Ita', 'email' => 'ietha.ochta@gmail.com'],
            ['name' => 'Muhammad Sulthoni Wibowo', 'email' => 'sulthoni81@gmail.com'],
            ['name' => 'putri kartika sari', 'email' => 'putriases85@gmail.com'],
            ['name' => 'Sri ramadani', 'email' => 'sriramadani9501@gmail.com'],
            ['name' => 'Tulus Pambudi', 'email' => 'farzanafcpbg@gmail.com'],
            ['name' => 'Ratlimah', 'email' => 'azzurabanafsha16@gmail.com'],
            ['name' => 'Mayang Tungga Dewi', 'email' => 'Mayanghidayat59@gmail.com'],
            ['name' => 'Aqidah Tin Sholihah', 'email' => 'aqidahsholihah07@gmail.com'],
            ['name' => 'Reny aminata', 'email' => 'renyaminata1@gmail.com'],
            ['name' => 'Marlina Anggraeni Sileuw', 'email' => 'marlinasileuw02@gmail.com'],
            ['name' => 'Dellia Oktafiani', 'email' => 'delliaoktafiani@gmail.com'],
            ['name' => 'Novi Fransiska', 'email' => 'Initehnovi.frnsiska@gmail.com'],
            ['name' => 'Wiwik Monoarfa', 'email' => 'monoarfawiwik@gmail.com'],
            ['name' => 'Anissa wening', 'email' => 'anissa.wening21@gmail.com'],
            ['name' => 'Diah Miarna Sari', 'email' => 'vitoazami@gmail.com'],
            ['name' => 'Nurhasanah', 'email' => 'noerforefry@gmail.com'],
            ['name' => 'Nofa Marda Aini', 'email' => 'nofamarda@gmail.com'],
            ['name' => 'Mieke erda gustria', 'email' => 'mieke854@gmail.com'],
            ['name' => 'Risti', 'email' => 'nenekkebayan0707@gmail.com'],
            ['name' => 'Iswatiningsih', 'email' => 'ningsihiswati9@gmail.com'],
            ['name' => 'Nihayatus Sa\'adah', 'email' => 'shofiyyahazzahidah@gmail.com'],
            ['name' => 'Desi Permata Sari', 'email' => 'desipermatas0112@gmail.com'],
            ['name' => 'Dewi Lisnawati', 'email' => 'dewilisnawati82@gmail.com'],
            ['name' => 'Firdiani', 'email' => 'firdydiany22@gmail.com'],
            ['name' => 'Ema Vidiastuti Utami', 'email' => 'emavidia@gmail.com'],
            ['name' => 'NUR AWALIAH WADUBUN', 'email' => 'awaliahwadubun08@gmail.com'],
            ['name' => 'Riono', 'email' => 'asykarzuhdi@gmail.com'],
            ['name' => 'Siti Hardianti', 'email' => 'yhanti102@gmail.com'],
            ['name' => 'Vina Hartati', 'email' => 'toko.umihawa@gmail.com'],
            ['name' => 'Fauziah nurhakiki', 'email' => 'fauziahnurhakiki@gmail.com'],
            ['name' => 'Nova veradita', 'email' => 'novaveradita@gmail.com'],
            ['name' => 'Misa Mahfud, S.Ag, M.A', 'email' => 'dpwagpaiijakarta@gmail.com'],
            ['name' => 'Imas indriyani', 'email' => 'indriyanimaxi27@gmail.com'],
            ['name' => 'resiga anirna pasa', 'email' => 'gaaradolphin@gmail.com'],
            ['name' => 'NOR ISAWAN', 'email' => 'ISAWAN911@GMAIL.COM'],
            ['name' => 'SAIMA NURAENI GUMAY', 'email' => 'saimagumay@gmail.com'],
            ['name' => 'MOHAMAD RIZAL ABDILLAH, S.Tr.Sos.,M.M', 'email' => 'zaliizal40@gmail.com'],
            ['name' => 'Dian Permata Sari', 'email' => 'dian918@guru.sd.belajar.id'],
            ['name' => 'Fiani Harsamil', 'email' => 'fianybagus@gmail.com'],
            ['name' => 'Muhammad Jaya Basthomy', 'email' => 'jbasthomy@gmail.com'],
            ['name' => 'Hikmah Restu Akhiriyah', 'email' => 'hikmahrestu17@gmail.com'],
            ['name' => 'Helmi Hardianti', 'email' => 'mrs.hardianti@gmail.com'],
            ['name' => 'Wida Martowardoyo', 'email' => 'ibumarto@gmail.com'],
            ['name' => 'epi nurhapijah', 'email' => 'quenbiee@gmail.com'],
            ['name' => 'Imas Dewi Hasanah', 'email' => 'imastheunyil@gmail.com'],
            ['name' => 'Lesta', 'email' => 'Ummumaudy28@gmail.com'],
            ['name' => 'Melinda Rahmawati', 'email' => 'melinda_rahma90@yahoo.com'],
            ['name' => 'Risky hikmi', 'email' => 'riskyhikmi95@gmail.com'],
            ['name' => 'Tanti Priyani', 'email' => 'tantipriyani1988@gmail.com'],
            ['name' => 'Ratna dayanti', 'email' => 'ratnadayanti290@gmail.com'],
            ['name' => 'EFTALISA KURNIA', 'email' => 'eftalisakurnia@gmail.com'],
            ['name' => 'Bruri Dwi Kurniawan', 'email' => 'bruridwikurniawan6@gmail.com'],
            ['name' => 'Mawaddatur Rohmah', 'email' => 'Mawaddaturohmah8@gmail.com'],
            ['name' => 'Ayyuhan Maulana', 'email' => 'yuhanmaulana64@gmail.com'],
            ['name' => 'Wiwik Nurhayati', 'email' => 'songoagung8@gmail.com'],
            ['name' => 'HARDIANA, S. ST', 'email' => 'hardianauzitawan@gmail.com'],
            ['name' => 'Isniatul Fadillah', 'email' => 'fadillahisniatul@gmail.com'],
            ['name' => 'IIN DIAN HARYATI HASYIM', 'email' => 'indhy.godness@gmail.com'],
            ['name' => 'WAWAN EFENDI', 'email' => 'wefendiw@gmail.com'],
            ['name' => 'Agustina', 'email' => 'agstn.shf@gmail.com'],
            ['name' => 'Yeniarti Maria Yanuarini', 'email' => 'yenimaria813@gmail.com'],
            ['name' => 'Rahma yofi', 'email' => 'rahma.yofi@gmail.com'],
            ['name' => 'Kamilah arikah syahbana', 'email' => 'Kamilaharikah23@gmail.com'],
            ['name' => 'Erna dwi rohma wati', 'email' => 'ernadwi2001@gmail.com'],
            ['name' => 'MARIA SUNITA', 'email' => 'mariasunita567@gmail.com'],
            ['name' => 'Pebruana Rahmawati', 'email' => 'innepradana20@gmail.com'],
            ['name' => 'AFDUNG AJI NURCAHYO', 'email' => 'afdungaji@gmail.com'],
            ['name' => 'Moedjiahtini', 'email' => 'moedjiahtini@gmail.com'],
            ['name' => 'Nur Alfia', 'email' => 'Ronipau56@gmail.com'],
            ['name' => 'Nuryani Wuryandari', 'email' => 'abinmifta@gmail.com'],
            ['name' => 'Lukman Hakim', 'email' => 'Lukmanadmproject@gmail.com'],
            ['name' => 'Fatimah', 'email' => 'fatimahazy23@gmail.com'],
            ['name' => 'Harjuma', 'email' => 'harjumachem@gmail.com'],
            ['name' => 'Efranto MC', 'email' => 'mcefranto0394@gmail.com'],
            ['name' => 'Deasita Shanti Mora', 'email' => 'deasitashantimora12@gmail.com'],
            ['name' => 'Erry hariyani', 'email' => 'erry.hariyani12@gmail.com'],
            ['name' => 'Cahyani Wulandari', 'email' => 'cahyaniwulan82@gmail.com'],
            ['name' => 'Sulastri', 'email' => 'achi.sulastri1990@gmail.com'],
            ['name' => 'Aprilia Winanda Miriyanti', 'email' => 'ubiku2023@gmail.com'],
            ['name' => 'Desi Rosmitasari', 'email' => 'Deasyrosmi06@gmail.com'],
            ['name' => 'Sahrul Karim', 'email' => 'shrulkarim@gmail.com'],
            ['name' => 'Andi pranata', 'email' => 'anditenggar86@gmail.com'],
            ['name' => 'Hurul Ainun P', 'email' => 'hurulainun7@gmail.com'],
            ['name' => 'Henny Juliati', 'email' => 'juliatihenny88@gmail.com'],
            ['name' => 'Amelia Sabella', 'email' => 'ameliasabella18@gmail.com'],
            ['name' => 'Nur Sholikah MJ', 'email' => 'enunk16@gmail.com'],
            ['name' => 'Muammar Hijaz', 'email' => 'ammar.jaaz@gmail.com'],
            ['name' => 'Khadijah Siregar', 'email' => 'khadijahdjregar@gmail.com'],
            ['name' => 'Dian Septriana', 'email' => 'dianseptriana19@gmail.com'],
            ['name' => 'Guris Aghitsatur Rochmah', 'email' => 'aghitsatur@gmail.com'],
            ['name' => 'Nuridah', 'email' => 'iidhasan9@gmail.com'],
            ['name' => 'Diana Marantika', 'email' => 'dianamarantika75@gmail.com'],
            ['name' => 'Ahmad Jimly Ashari', 'email' => 'ajimlyashari@gmail.com'],
            ['name' => 'Ika Widya Oktaviana sari', 'email' => 'ikawospacitan@gmail.com'],
            ['name' => 'Ima febri irfani', 'email' => 'imafebri98@gmail.com'],
            ['name' => 'Darmawati', 'email' => 'Darmawati9145@gmail.com'],
            ['name' => 'Lola Permatasari', 'email' => 'lolapermatasari100@gmail.com'],
            ['name' => 'Indah Kurniyawati', 'email' => 'indahkurniyawati271821@gmail.com'],
            ['name' => 'Yuli Safitri', 'email' => 'yulisa.fitri1317@gmail.com'],
            ['name' => 'Lathifah Maryam', 'email' => 'ifahalafgani@gmail.com'],
            ['name' => 'Uswatun Khasanah', 'email' => 'u2samini@gmail.com'],
            ['name' => 'Shohifatul Izzah', 'email' => 'shohifaizzah@gmail.com'],
            ['name' => 'Mulyadi Selian', 'email' => 'jb.mulyadi30@gmail.com'],
            ['name' => 'Nanda Ekawati Dahlya', 'email' => 'nanda.ekawati10@guru.smk.belajar.id'],
            ['name' => 'Atia Muflihanna', 'email' => 'atia.mufli@gmail.com'],
            ['name' => 'Kun Muthia Adiba Rahmadianti', 'email' => 'muthiaadiba88@gmail.com'],
            ['name' => 'Dhini Ulfia Kinan', 'email' => 'nadinenazz@gmail.com'],
            ['name' => 'Aprilya Azizah', 'email' => 'aprilya.azizah01@gmail.com'],
            ['name' => 'Fitri Annisa Hayati', 'email' => 'fitri.annisa.hayati@gmail.com'],
            ['name' => 'Siti kholillah', 'email' => 'nijarnijar582@gmail.com'],
            ['name' => 'Kurrata Aini', 'email' => 'myaycozy@gmail.com'],
            ['name' => 'Daniah Mumtaza', 'email' => 'mumtaza1994@gmail.com'],
            ['name' => 'SANTI LESTARI', 'email' => 'santilestari248@gmail.com'],
            ['name' => 'Oktiza Yelhazeni', 'email' => 'oktizayelhazeni@gmail.com'],
            ['name' => 'Friyati', 'email' => 'Upifriyati@gmail.com'],
            ['name' => 'Khusnul Khotimah', 'email' => 'h2c2habibi@gmail.com'],
            ['name' => 'Rini Pujiastuti', 'email' => 'Rini_lenka@yahoo.co.id'],
            ['name' => 'Sudarnengsi Bachtiar', 'email' => 'nengsibachtiar@gmail.com'],
            ['name' => 'Bebby Angela', 'email' => 'angelabebby.123@gmail.com'],
            ['name' => 'ASRAMADHANI', 'email' => 'dhaniasrama@gmail.com'],
            ['name' => 'Anggrahesti', 'email' => 'callmehesti@gmail.com'],
            ['name' => 'Lovina Velesia Ilma', 'email' => 'lovinailmas@gmail.com'],
            ['name' => 'Royani', 'email' => 'royanidn22@gmail.com'],
            ['name' => 'Vyanna Mahfuza', 'email' => 'vyannamahfuza@gmail.com'],
            ['name' => 'Mirianti Harjawijaya', 'email' => 'Mellylady@gmail.com'],
            ['name' => 'Riskan Maulana', 'email' => 'ark.rmaulana@gmail.com'],
            ['name' => 'Luvita Febiola Adabiyah', 'email' => 'febiolaluvita5@gmail.com'],
            ['name' => 'Mutiara Sari Nur Azizah', 'email' => 'drmutiarasari@gmail.com'],
            ['name' => 'Nanik Utami', 'email' => 'kinan.imatu3@gmail.com'],
            ['name' => 'Aulia Andaryati', 'email' => 'auliaandaryati@gmail.com'],
            ['name' => 'Masdalila Nasution', 'email' => 'Mdlnst23@gmail.com'],
            ['name' => 'asri hartati', 'email' => 'bee.aci@gmail.com'],
            ['name' => 'Fifi Eka Nur Rahmawati', 'email' => 'fenra18@gmail.com'],
            ['name' => 'Intan Puspitaningrum', 'email' => 'afghanikrishna@gmail.com'],
            ['name' => 'Irma Warang', 'email' => 'irma.amx113@gmail.com'],
            ['name' => 'Elry Dwi Novryaningsih', 'email' => 'elzafaya.04@gmail.com'],
            ['name' => 'Fira Nursafitri', 'email' => 'Fira.nursaf@gmail.com'],
            ['name' => 'Dwi septiani', 'email' => 'Sebataspandang24@gmail.com'],
            ['name' => 'Lenny Zul\'agfiani', 'email' => 'Lyzfi085@gmail.com'],
            ['name' => 'Dian Endah Puspitasari', 'email' => 'de.puspitasari.ae@gmail.com'],
            ['name' => 'Nur Diana Khalidah', 'email' => 'nurdiana.khalidah@gmail.com'],
            ['name' => 'Nurwigati Ningrum', 'email' => 'gati_undip74@yahoo.co.id'],
            ['name' => 'Rini Kadarwati', 'email' => 'rinikadarwati1986@gmail.com'],
            ['name' => 'Umairoh Lisa’adah', 'email' => 'umairroh28@gmail.com'],
            ['name' => 'Nurlela', 'email' => 'nurlelaasanofa@gmail.com'],
            ['name' => 'Hanif Nusrotul Azizah', 'email' => 'hnusrotul@gmail.com'],
            ['name' => 'Kurnia Siwi Hastuti', 'email' => 'hastutiksexacta2@gmail.com'],
            ['name' => 'Nuliya Shinta', 'email' => 'nuliasinta114@gmail.com'],
            ['name' => 'Chairani putri nasution', 'email' => 'ranichai700@gmail.com'],
            ['name' => 'Indrajaya', 'email' => 'indrajayarahmat124@gmaila.com'],
            ['name' => 'Ratna Fitriani Imanita', 'email' => 'ratnafitriani8@gmail.com'],
            ['name' => 'EGI MUHAMAD NUGRAHA', 'email' => 'eggimuhamadnugraha2002@gmail.com'],
            ['name' => 'Ratnasari Pamungkas', 'email' => 'ratnasaripamungkas990@gmail.com'],
            ['name' => 'Kantika lestari', 'email' => 'kantikalestari51@gmail.com'],
            ['name' => 'Utin Murlina', 'email' => 'utinmurlina@gmail.com'],
            ['name' => 'SISWAHONO', 'email' => 'siswahono828@gmail.com'],
            ['name' => 'Leni Agustika', 'email' => 'lenibappeda@gmail.com'],
            ['name' => 'Hernita Sabarhayati', 'email' => 'hernita7172@gmail.com'],
            ['name' => 'dwi mariastuty', 'email' => 'dwimariastuty1803@gmail.com'],
            ['name' => 'Ani Mufarohah', 'email' => 'anismufarohahzainul@gmail.com'],
            ['name' => 'Yuliati Wahyuningsih', 'email' => 'yuliatiwahyuningsih2016@gmail.com'],
            ['name' => 'DIAN KARUNIA', 'email' => 'keuangan.keppwt@gmail.com'],
            ['name' => 'Widiya Wati', 'email' => 'widiya.imuetz37@gmail.com'],
            ['name' => 'Ristaqul Husna Belgania', 'email' => 'rhbelgania@gmail.com'],
            ['name' => 'Dinka candra yusnita', 'email' => 'dinkapkmtembokrejo@gmail.com'],
            ['name' => 'Yuliana febrianti', 'email' => 'yulieabdurahman2025@gmail.com'],
            ['name' => 'Najiya Arroisi', 'email' => 'jiya.arroisi@gmail.com'],
            ['name' => 'Souvia Nabila', 'email' => 'souvianabila@yahoo.com'],
            ['name' => 'Prama Mulyati', 'email' => 'pm.pramamulyati@gmail.com'],
            ['name' => 'ETI ERMAWATI', 'email' => 'etiermma88@gmail.com'],
            ['name' => 'Yushadi Taufik', 'email' => 'aprisaaza@gmail.com'],
            ['name' => 'Enda Arova Rohmatuka', 'email' => 'ndarova@gmail.com'],
            ['name' => 'Nur Fitriani', 'email' => 'nurfitrianiii351@gmail.com'],
            ['name' => 'Khairun Nisa', 'email' => 'runisa96@gmail.com'],
            ['name' => 'Yulia Indah Juwita', 'email' => 'dodikandry88@gmail.com'],
            ['name' => 'RENVY Hardianty', 'email' => 'renvyhardianty86@gmail.com'],
            ['name' => 'Hikmah AS', 'email' => 'hikmah.abdulsyukur@gmail.com'],
            ['name' => 'Fadhila Akhwalil Isnaeni', 'email' => 'fadhilaakhwalil@gmail.com'],
            ['name' => 'Reny Rachmalia', 'email' => 'renyrachmalia17@gmail.com'],
            ['name' => 'Wulandari alwinda puspasari', 'email' => 'wulandarialwinda@gmail.com'],
            ['name' => 'Rahmat Asikin', 'email' => 'rahmatasikin1@gmail.com'],
            ['name' => 'Neli Sunarni', 'email' => 'nelisunarni13@gmail.com'],
            ['name' => 'Afrianti Azis', 'email' => 'afrianti.azis82@gmail.com'],
            ['name' => 'Rifqatul Auliya Hasbullah', 'email' => 'rifqaauliya13@gmail.com'],
            ['name' => 'Annisa Dwinda Shafira', 'email' => 'Annisadwindashafira@gmail.com'],
            ['name' => 'Weni mustika sari', 'email' => 'wenimustika@gmail.com'],
            ['name' => 'Zahrulia Arina Rinanda', 'email' => 'z.asyifa88@gmail.com'],
            ['name' => 'Indo Sennang', 'email' => 'indosennang111@gmail.com'],
            ['name' => 'Oktavenyta Eriana', 'email' => 'oktavenyta27@gmail.com'],
            ['name' => 'Nurhayati', 'email' => 'nagizaobi@gmail.com'],
            ['name' => 'Angga Adhyarini', 'email' => 'angga.adhya02@gmail.com'],
            ['name' => 'Addina Hidayati', 'email' => 'luqmanantaaddina@gmail.com'],
            ['name' => 'Aprilia Asterina Hutomo', 'email' => 'hutomoaprilia@gmail.com'],
            ['name' => 'Noviyanti', 'email' => 'novhymmr@gmail.com'],
            ['name' => 'RATU NISA SHAFIRA HERMAWAN', 'email' => 'shafirahermawan16@gmail.com'],
            ['name' => 'Atiqotul Maula Alfarihah', 'email' => 'alfarihahatiqotul@gmail.com'],
            ['name' => 'Nur Sofi Wulandari', 'email' => 'nsofiwulandari@gmail.com'],
            ['name' => 'Widya Aulia Riski Siregar', 'email' => 'widyaauliariskisiregar@gmail.com'],
            ['name' => 'Adelia Pravitaningtiyas', 'email' => 'dhelia.pamungkas@gmail.com'],
            ['name' => 'Yogi Hendra Pratiwi', 'email' => 'pratiwiyogihendra@gmail.com'],
            ['name' => 'Sam Hilda Nadia Hidayah', 'email' => 'nadia.hilda27@gmail.com'],
            ['name' => 'Ayu Kinasih', 'email' => 'tanyakak.ayuk@gmail.com'],
            ['name' => 'Maulida', 'email' => 'annida.oriflame@gmail.com'],
            ['name' => 'Hertini', 'email' => 'hertini123@gmail.com'],
            ['name' => 'Erni Chikmahwati', 'email' => 'chikmahwati.erni@gmail.com'],
            ['name' => 'nonoi oktarina', 'email' => 'nonoioktarinaamd@gmail.com'],
            ['name' => 'Yetti Hidayatillah', 'email' => 'upisumenep25@gmail.com'],
            ['name' => 'St Nurjannah', 'email' => 'stnurjannahnnn38@gmail.com'],
            ['name' => 'M Ridho Maulana', 'email' => 'maulanakingdom@gmail.com'],
            ['name' => 'Desi Esta Putri Perdana', 'email' => 'desiestaputri@gmail.com'],
            ['name' => 'Nur Kumala', 'email' => 'Nurkumala1178@gmail.com'],
            ['name' => 'Ike Sri Wahyuni', 'email' => 'Ikesriwahyuni0@gmail.com'],
            ['name' => 'Dessy Arisna', 'email' => 'dessyarisna99@gmail.com'],
            ['name' => 'Dzi Fahminnafi', 'email' => 'dzifahminnafi@gmail.com'],
            ['name' => 'mariyah ulfah', 'email' => 'duwan.536@gmail.com'],
            ['name' => 'IIS ISMAWATI LATIFAH', 'email' => 'ismawati81latifah@gmail.com'],
            ['name' => 'Siti Sarah', 'email' => 'desitisarah@upi.edu'],
            ['name' => 'Nursaleh', 'email' => 'masdzol22@gmail.com'],
            ['name' => 'Yulianty Pratiwi', 'email' => 'yulipratiwie77@gmail.com'],
            ['name' => 'Dian kurnianingsih', 'email' => 'diankurnia307@gmail.com'],
            ['name' => 'Yuni Purwati', 'email' => 'yunifadillah69@gmail.com'],
            ['name' => 'Annisauzzahroh Nur Afifah', 'email' => 'afifannisa731@gmail.com'],
            ['name' => 'Dona Uly Indrawaty', 'email' => 'donaulyindrawaty@gmail.com'],
            ['name' => 'Yulianingsih', 'email' => 'yuliarend@gmail.com'],
            ['name' => 'Nurhalizah Fadila Capah', 'email' => 'zahcapah@gmail.com'],
            ['name' => 'Nur Asgaf Ramadona', 'email' => 'nurasgaframadona11@gmail.com'],
            ['name' => 'NURPARIDA', 'email' => 'farida.azib17@gmail.com'],
            ['name' => 'Riska rosiana', 'email' => 'Riska.rosiana18@gmail.com'],
            ['name' => 'Rahmadony', 'email' => 'rahmadony46@gmail.com'],
            ['name' => 'Lilik Triyani', 'email' => 'tlilik478@gmail.com'],
            ['name' => 'Citra Amanda', 'email' => 'citramand@gmail.com'],
            ['name' => 'Widiati Pratiwi', 'email' => 'widiatipratiwi@gmail.com'],
            ['name' => 'Silvia Triana Indriyanti', 'email' => 'silviatriana185@gmail.com'],
            ['name' => 'Rohanah asnawati', 'email' => 'anhaasnawati06@gmail.com'],
            ['name' => 'Ira dwi', 'email' => 'Ira0908@gmail.com'],
            ['name' => 'Titin Sumarni', 'email' => 'titinsumarni806@gmail.com'],
            ['name' => 'Trinna Valentina', 'email' => 'trinna.anet.valentina@gmail.com'],
            ['name' => 'Nawira Kurniawati', 'email' => 'nanawiwirara@gmail.com'],
            ['name' => 'Annisa Dzunnurain', 'email' => 'dzunnurainannisa@gmail.com'],
            ['name' => 'Putri Rahmawani', 'email' => 'putri230894@gmail.com'],
            ['name' => 'Fadliyah', 'email' => 'ffadliyah123@gmail.com'],
            ['name' => 'Rahmi Kholida', 'email' => 'rahmikholida906@gmail.com'],
            ['name' => 'Nur tsabitah al mujahidah', 'email' => 'n.tsabitah21@gmail.com'],
            ['name' => 'Ade chandra kurniawan', 'email' => 'Achandra2410@gmail.com'],
            ['name' => 'Nur lestari', 'email' => 'nur.lestari992@gmail.com'],
            ['name' => 'A. HAMAM ROSIDI', 'email' => 'hamamrosidi@gmail.com'],
            ['name' => 'Atiq rifqi muakhiroh', 'email' => 'chevidana@gmail.com'],
            ['name' => 'resky', 'email' => 'kikinazarr@gmail.com'],
            ['name' => 'Roudhlotul Jannah', 'email' => 'zahiyah1453@gmail.com'],
            ['name' => 'Untari Lisya Kurniawati', 'email' => 'untarilisyaya@gmail.com'],
            ['name' => 'Dina adriana wulandari', 'email' => 'wulandari03883@gmail.com'],
            ['name' => 'Nurul oktavia putri', 'email' => 'Nuruloktavia.akunpribadi@gmail.com'],
            ['name' => 'Nanda Sartika', 'email' => 'nandasartika332@gmail.com'],
            ['name' => 'Pragata Okti Andarini', 'email' => 'pragataoktia16@gmail.com'],
            ['name' => 'Zelis febriani', 'email' => 'zelisfebriani@gmail.com'],
            ['name' => 'Fadhilah Lestari', 'email' => 'Ar.fadhilahl@gmail.com'],
            ['name' => 'TUTY ERLINAWATY SIREGAR', 'email' => 'tutyerlinawaty1988@gmail.com'],
            ['name' => 'Fajar Tri Prabowo', 'email' => 'Fajartriprabowo@gmail.com'],
            ['name' => 'Meliani Sri Rahayu', 'email' => 'melianisrr@gmail.com'],
            ['name' => 'rahma', 'email' => 'rhmbukhari@gmail.com'],
            ['name' => 'iqbal maulana', 'email' => 'iqbalmaulana1414@gmail.com'],
            ['name' => 'restiyulianita', 'email' => 'restiyuliyanita@gmail.com'],
            ['name' => 'Novis Prasetyawan', 'email' => 'novisprasetyawan@gmail.com'],
            ['name' => 'Iska Nur Puspitasari', 'email' => 'iska2bill@gmail.com'],
            ['name' => 'HANA HULIYAH', 'email' => 'hanahulia2@gmail.com'],
            ['name' => 'Anike', 'email' => 'anikeputri.jefany@gmail.com'],
            ['name' => 'ROHMIATI', 'email' => 'Rohmiomi95@gmail.com'],
            ['name' => 'Lulus indraaati', 'email' => 'lulusindrawati100@gmail.com'],
            ['name' => 'Dian Ajizah', 'email' => 'dianajizah94@gmail.com'],
            ['name' => 'RETNO DWI HARIATI', 'email' => 'retnodwihariati425@gmail.com'],
            ['name' => 'Yeni Octavia', 'email' => 'octaviayeni90@gmail.com'],
            ['name' => 'Slamet Yulianto', 'email' => 'yuliahmad26@gmail.com'],
            ['name' => 'FITRIYAH', 'email' => 'fitriyahfafafa@gmail.com'],
            ['name' => 'Ade moqita bahran', 'email' => 'ade.moqita@gmail.com'],
            ['name' => 'DALFILA', 'email' => 'defiedelfie@gmail.com'],
            ['name' => 'Sari Narulita', 'email' => 'Ehsasari@gmail.com'],
            ['name' => 'Arip Mulyana', 'email' => 'faniaria021@gmail.com'],
            ['name' => 'Ika Rahma Yanti', 'email' => 'ikarahmayanti18@gmail.com'],
            ['name' => 'Ade Afifah Fajria Suroto', 'email' => 'adeafifah888@gmail.com'],
            ['name' => 'Reni Indrawati', 'email' => 'ismireni0k@gmail.com'],
            ['name' => 'RIZKI NOVIDIA', 'email' => 'qnvidia.rn@gmail.com'],
            ['name' => 'Dian Fauzia Chairunisa', 'email' => 'Diananisa100493@gmail.com'],
            ['name' => 'Embun Rahmawati', 'email' => 'Mbunrahmawati@gmail.com'],
            ['name' => 'Dewi Fatimah', 'email' => 'dewifb70@gmail.com'],
            ['name' => 'ranty herviana', 'email' => 'rantyherviana20@gmail.com'],
            ['name' => 'Norma Ita Sholichah', 'email' => 'normaita@alqolam.ac.id'],
            ['name' => 'Septian Eko Cahyono', 'email' => 'septianekocahyono92@gmail.com'],
            ['name' => 'Vini Nuraeni', 'email' => 'vininuraeni02@gmail.com'],
            ['name' => 'Suri', 'email' => 'Suriaisyahas@gmail.com'],
            ['name' => 'Fitri sari', 'email' => 'fit3sari@gmail.com'],
            ['name' => 'Nia rohatin', 'email' => 'niarsoleh04@gmail.com'],
            ['name' => 'Shofiyatul Maula', 'email' => 'shofiyamaula24@gmail.com'],
            ['name' => 'Richanatul jannah', 'email' => 'richanatuljannah@gmail.com'],
            ['name' => 'Nur Indah', 'email' => 'nauraindah13@gmail.com'],
            ['name' => 'Diyana niken pramita', 'email' => 'diyananiken90@gmail.com'],
            ['name' => 'FARICHATUL LATIFAH, S.Pd.I', 'email' => 'farichatul.latifah.fl@gmail.com'],
            ['name' => 'Ika Farkha Widiyanti', 'email' => 'ikaafarkhawidiyanti30@gmail.com'],
            ['name' => 'Efy syahriyani', 'email' => 'syahriani.efy@gmail.com'],
            ['name' => 'anisatul fauziyah', 'email' => 'anisatulfauziyah8@gmail.com'],
            ['name' => 'Syaripudin', 'email' => 'syaripudinbusrah4@gmail.com'],
            ['name' => 'Farokhi Dawin Ni\'am', 'email' => 'farokhidawin@gmail.com'],
            ['name' => 'SRI MEGA UTAMI', 'email' => 'srimegautami4@gmail.com'],
            ['name' => 'Melinawati', 'email' => 'melinawati0231@gmail.com'],
            ['name' => 'Komariah', 'email' => 'azam.munandar14@gmail.com'],
            ['name' => 'Nur Khasanah', 'email' => 'nunghasa3.enha16@gmail.com'],
            ['name' => 'Erlita Fitri Hikmawati', 'email' => 'erlitalicius@gmail.com'],
            ['name' => 'Dyah Sri Utami', 'email' => 'dyah16capricorn@gmail.com'],
            ['name' => 'Fitri Anna', 'email' => 'nazarfitria36@gmail.com'],
            ['name' => 'Nur Azizah Anshar', 'email' => 'ummuhanif1285@gmail.com'],
        ];

        /// 2. Masukkan data member yang baru
        DB::transaction(function () use ($members, $course) {
            foreach ($members as $member) {
                $user = User::create([
                    'name' => $member['name'],
                    'email' => $member['email'],
                    'password' => Hash::make('password'),
                    'role' => 'member',
                    'foto_profile' => null,
                    'alamat' => null,
                    'pekerjaan' => null,
                    'status' => null, // PERBAIKAN: Diubah jadi null agar tidak crash dengan aturan ENUM (menikah/belum)
                    'status_akun' => 'aktif', // Ini yang benar menggunakan 'aktif'
                ]);

                // Buatkan transaksi sukses otomatis untuk kelas terkait
                $transaction = Transaction::create([
                    'user_id' => $user->id,
                    'kode_transaksi' => 'AUTO-' . date('Ymd') . '-' . strtoupper(uniqid()),
                    'total_harga' => $course->harga ?? 0, 
                    'status' => 'verified', 
                    'bukti_pembayaran' => 'Sistem Otomatis (Seeder)',
                ]);

                // Hubungkan transaksi ke tabel pivot course_transaction
                $transaction->courses()->attach($course->id, [
                    'harga_saat_beli' => $course->harga ?? 0
                ]);
            }
        });
        
        $this->command->info('Refresh Selesai: ' . count($members) . ' member baru berhasil disuntikkan kembali ke kelas "' . $course->nama . '".');
    }
}